theme: jekyll-theme-minimal
title: AI4Copernicus tools and methods for bridging AI and EO
description: >
  Half-day tutorial at BiDS 2023.
logo: https://ai4copernicus-project.eu/wp-content/uploads/2021/06/AI4Copernicus_-logo-transparent.png
show_downloads: false
